### ISSUE TITLE
Mod crash when click F9

### ISSUE THREAD

**Issue by Array-Cats** [pascallj/mineshot-revived-fabric#1]
Log

```
Command: "C:\\Program Files\\Java\\jre1.8.0_291\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.16.5\1.16.5.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Djava.library.path=D:\\Downloads\\Minecraft test fa\\.minecraft\\versions\\1.16.5\\natives" -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.188 -cp "D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\tiny-mappings-parser\\0.2.2.14\\tiny-mappings-parser-0.2.2.14.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\sponge-mixin\\0.9.2+mixin.0.8.2\\sponge-mixin-0.9.2+mixin.0.8.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\tiny-remapper\\0.3.0.70\\tiny-remapper-0.3.0.70.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\access-widener\\1.0.0\\access-widener-1.0.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader-sat4j\\2.3.5.4\\fabric-loader-sat4j-2.3.5.4.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\google\\jimfs\\jimfs\\1.2-fabric\\jimfs-1.2-fabric.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\ow2\\asm\\asm\\9.1\\asm-9.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\ow2\\asm\\asm-analysis\\9.1\\asm-analysis-9.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\ow2\\asm\\asm-commons\\9.1\\asm-commons-9.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\ow2\\asm\\asm-tree\\9.1\\asm-tree-9.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\ow2\\asm\\asm-util\\9.1\\asm-util-9.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\intermediary\\1.16.5\\intermediary-1.16.5.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader\\0.11.3\\fabric-loader-0.11.3.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\patchy\\1.1\\patchy-1.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\ibm\\icu\\icu4j\\66.1\\icu4j-66.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\datafixerupper\\4.0.26\\datafixerupper-4.0.26.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\authlib\\2.1.28\\authlib-2.1.28.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;D:\\Downloads\\Minecraft test fa\\.minecraft\\versions\\1.16.5\\1.16.5.jar" net.fabricmc.loader.launch.knot.KnotClient --username Array_Cats --version "HMCL 3.3.188" --gameDir "D:\\Downloads\\Minecraft test fa\\.minecraft" --assetsDir "D:\\Downloads\\Minecraft test fa\\.minecraft\\assets" --assetIndex 1.16 --uuid 4544fba42206471cbc36eb9f0f3cfab8 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZGM0ZDFiNjBiYTFkOGJhYzFmODM2YjU5YjY5ZmYzOSIsInlnZ3QiOiJmNGNmZWM0MTdkODI0MjllOTUwZmJiYTliNTRlZGJiYiIsInNwciI6IjQ1NDRmYmE0MjIwNjQ3MWNiYzM2ZWI5ZjBmM2NmYWI4IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MjM4MjE4MDAsImlhdCI6MTYyMzY0OTAwMH0.Al4CU1nmjlspWSzgGnB_2adMIRh5h0Y48Ok-Mx9Pess --userType mojang --versionType "HMCL 3.3.188" --width 854 --height 480
[13:47:48] [main/INFO]: Loading for game Minecraft 1.16.5
[13:47:49] [main/INFO]: [FabricLoader] Loading 49 mods: fabric-renderer-api-v1@0.4.3+0ef801b67d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.3, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+61336ba97d, fabric-object-builder-api-v1@1.9.5+c88702897d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.35.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.1.0+731c05f37d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, modmenu@1.16.9, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-entity-events-v1@1.1.0+c88702897d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, mineshotrevived@1.0.0, fabric-resource-loader-v0@0.4.6+2868a2287d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.10+3661eaa17d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.3+e3c9d0627d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[13:47:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/Downloads/Minecraft%20test%20fa/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[13:47:54] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:47:55] [main/INFO]: Setting user: <player>
[13:47:56] [main/INFO]: [Indigo] Registering Indigo renderer!
[13:47:56] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[13:47:58] [main/INFO]: Narrator library for x64 successfully loaded
[13:47:58] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Crash Report Info (v1), Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Mineshot Revived, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[13:48:01] [main/INFO]: OpenAL initialized.
[13:48:01] [main/INFO]: Sound engine started
[13:48:02] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[13:48:02] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:48:02] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:48:02] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:48:02] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:48:02] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:48:02] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:48:02] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:48:02] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:48:02] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:48:06] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:48:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:48:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:48:06] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:48:06] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:48:06] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[13:48:06] [main/INFO]: Loaded 7 recipes
[13:48:06] [main/INFO]: Loaded 927 advancements
[13:48:06] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.312 ms
[13:48:07] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:48:07] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[13:48:07] [Server thread/INFO]: Generating keypair
[13:48:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:48:08] [main/INFO]: 准备生成区域中：0%
[13:48:08] [main/INFO]: 准备生成区域中：0%
[13:48:09] [main/INFO]: 准备生成区域中：83%
[13:48:09] [main/INFO]: 准备生成区域中：83%
[13:48:09] [main/INFO]: 准备生成区域中：83%
[13:48:10] [main/INFO]: 准备生成区域中：97%
[13:48:10] [main/INFO]: Time elapsed: 2823 ms
[13:48:10] [Server thread/INFO]: Changing view distance to 11, from 10
[13:48:12] [Server thread/INFO]: <player>[local:E:f41fbf45] logged in with entity id 203 at (162.07708977553597, 66.0, 163.73623406011694)
[13:48:12] [Server thread/INFO]: <player>加入了游戏
[13:48:12] [Server thread/INFO]: Saving and pausing game...
[13:48:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[13:48:12] [main/INFO]: Loaded 0 advancements
[13:48:13] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[13:48:13] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[13:48:19] [main/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.buildTargaHeader(FramebufferWriter.java:42) ~[mineshot-revived-1.0.0.jar:?]
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.write(FramebufferWriter.java:33) ~[mineshot-revived-1.0.0.jar:?]
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.task.CaptureTask.onRenderTick(CaptureTask.java:47) ~[mineshot-revived-1.0.0.jar:?]
	at nl.pascalroeleven.minecraft.mineshotrevived.client.ScreenshotHandler.onRenderTick(ScreenshotHandler.java:60) ~[mineshot-revived-1.0.0.jar:?]
	at net.minecraft.class_758.handler$zge000$onRender(class_758.java:519) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_758.method_3210(class_758.java:181) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1116) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:727) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:546) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
[13:48:20] [Server thread/INFO]: Stopping server
[13:48:20] [Server thread/INFO]: Saving players
[13:48:20] [Server thread/INFO]: <player> lost connection: 连接中止
[13:48:20] [Server thread/INFO]: <player>退出了游戏
[13:48:20] [Server thread/INFO]: Stopping singleplayer server as player logged out
[13:48:20] [Server thread/INFO]: Saving worlds
[13:48:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界): All chunks are saved
[13:48:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:48:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界): All chunks are saved
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:48:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 21-6-14 下午1:48
Description: Unexpected error

java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.buildTargaHeader(FramebufferWriter.java:42)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.write(FramebufferWriter.java:33)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.task.CaptureTask.onRenderTick(CaptureTask.java:47)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.ScreenshotHandler.onRenderTick(ScreenshotHandler.java:60)
	at net.minecraft.class_758.handler$zge000$onRender(class_758.java:519)
	at net.minecraft.class_758.method_3210(class_758.java:181)
	at net.minecraft.class_761.method_22710(class_761.java:1116)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.buildTargaHeader(FramebufferWriter.java:42)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.FramebufferWriter.write(FramebufferWriter.java:33)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.capture.task.CaptureTask.onRenderTick(CaptureTask.java:47)
	at nl.pascalroeleven.minecraft.mineshotrevived.client.ScreenshotHandler.onRenderTick(ScreenshotHandler.java:60)
	at net.minecraft.class_758.handler$zge000$onRender(class_758.java:519)
	at net.minecraft.class_758.method_3210(class_758.java:181)
	at net.minecraft.class_761.method_22710(class_761.java:1116)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['<player>'/203, l='ClientLevel', x=162.08, y=66.00, z=163.74]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (152,63,158), Chunk: (at 8,3,14 in 9,9; contains blocks 144,0,144 to 159,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 638 game time, 638 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7865542960 bytes (7501 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		fabric: Fabric API 0.35.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+731c05f37d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		mineshotrevived: Mineshot Revived 1.0.0
		modmenu: Mod Menu 1.16.9
	Launched Version: HMCL 3.3.188
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 462.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: 简体中文 (中国)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
#@!@# Game crashed! Crash report saved to: #@!@# D:\Downloads\Minecraft test fa\.minecraft\crash-reports\crash-2021-06-14_13.48.21-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by pascallj** [comment]
This is a known problem when running some code compiled in Java 1.9+, in Java 1.8. For now you might want to upgrade to a newer version, but maybe I can make sure it's 1.8 compatible in the future.

**Comment by Array-Cats** [comment]
OK, I'm understand. thx to updating

**Comment by pascallj** [comment]
Btw, from Minecraft 1.17 onwards, Java 16 is required anyway so I'll be dropping 1.8 support completely.
